name: "Netbird"
description: "Connect Home Assistant to your Netbird network"
version: "1.2.0.62.2"
slug: "netbird"
init: false
arch:
  - amd64
network:
  mode: host
devices:
  - /dev/net/tun
privileged:
  - NET_ADMIN
options:
  endpoint: "https://netbird..."
  token: ""
  hostname: "HomeAssistant"
  homeassistant_ip: "192.168.x.x"
  homeassistant_port: 8123
  use_ssl: false
schema:
  endpoint: str
  token: str
  hostname: str
  homeassistant_ip: str
  homeassistant_port: int
  use_ssl: bool
